# Generated by Django 4.2.4 on 2023-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chadparba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Name of Katha')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Thumbnail Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description meaning of Katha')),
                ('youtube_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link of youtube video')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views Count of Katha')),
                ('tag', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tag of Katha')),
                ('realted_chadparba', models.ManyToManyField(blank=True, to='chadparba.chadparba', verbose_name='Related Chadparba')),
                ('realted_katha', models.ManyToManyField(blank=True, to='katha.katha', verbose_name='Related Katha')),
            ],
            options={
                'verbose_name_plural': 'Katha Haru',
            },
        ),
    ]
