# Generated by Django 4.2.4 on 2023-08-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poojabidhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poojabidhi',
            options={'verbose_name_plural': 'Pooja Bidhi Haru'},
        ),
    ]
