# Generated by Django 4.2.4 on 2023-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantra', '0002_alter_mantra_options'),
        ('poojabidhi', '0002_alter_poojabidhi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChadParba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Name of Chad Parba')),
                ('date_of_chad_ad', models.DateField(blank=True, null=True, verbose_name='Date of Chad Parba')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description of Chad Parba')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Preview Image')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views Count of Chad Parba')),
                ('related_chadparba', models.ManyToManyField(blank=True, to='chadparba.chadparba', verbose_name='Related Chad Parba')),
                ('related_mantra', models.ManyToManyField(blank=True, to='mantra.mantra', verbose_name='Related Mantra')),
                ('related_poojabidhi', models.ManyToManyField(blank=True, to='poojabidhi.poojabidhi', verbose_name='Related Pooja Bidhi')),
            ],
            options={
                'verbose_name_plural': 'Chad Parba Haru',
            },
        ),
    ]
