# Generated by Django 4.2.4 on 2023-08-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantra',
            options={'verbose_name_plural': 'Mantra Haru'},
        ),
    ]
